defaults:
  - default.yaml

trainer:
  accelerator: gpu
  devices: ${trainer.devices}
  sync_batchnorm: True
  precision: bf16-mixed
  strategy: ddp_find_unused_parameters_true
  num_nodes: 1

devices: 2
num_workers: 8