defaults:
  - network: FineTune_SemSeg
  - loss: CrossEntropyWeighted
  - train_metrics: metrics_segsem
  - val_metrics: metrics_segsem
  - test_metrics: metrics_segsem
  - _self_

name: RAMEN

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 15
  max_epochs: ${max_epochs}
  warmup_start_lr: 0.000001
  eta_min: 0.0000001

instance:
  _target_: src.models.module.Module
  optimizer: ${model.optimizer}
  scheduler: ${model.scheduler}
  network: ${model.network}
  loss: ${model.loss}
  train_metrics: ${model.train_metrics}
  val_metrics: ${model.val_metrics}
  test_metrics: ${model.test_metrics}
